let textBetweenSpacersHstack: [string: any][] = [
    {
       "id":0,
       "range":{
          "startColumn":1,
          "endRow":14,
          "endColumn":1,
          "startRow":1
       },
       "structure":[
          {
             "name":"unexpectedBeforeStatements",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"statements",
             "value":{
                "text":"CodeBlockItemListSyntax"
             },
             "ref":"CodeBlockItemListSyntax"
          },
          {
             "name":"unexpectedBetweenStatementsAndEOFToken",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"eofToken",
             "value":{
                "kind":"eof",
                "text":"↲"
             }
          },
          {
             "name":"unexpectedAfterEOFToken",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "text":"SourceFile"
    },
    {
       "text":"CodeBlockItemList",
       "id":1,
       "range":{
          "startColumn":1,
          "endRow":13,
          "endColumn":2,
          "startRow":1
       },
       "structure":[
          {
             "name":"Element",
             "value":{
                "text":"CodeBlockItemSyntax"
             }
          },
          {
             "name":"Count",
             "value":{
                "text":"2"
             }
          }
       ],
       "type":"collection",
       "parent":0
    },
    {
       "text":"CodeBlockItem",
       "id":2,
       "range":{
          "startColumn":1,
          "endRow":1,
          "endColumn":15,
          "startRow":1
       },
       "structure":[
          {
             "name":"unexpectedBeforeItem",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"item",
             "value":{
                "text":"ImportDeclSyntax"
             },
             "ref":"ImportDeclSyntax"
          },
          {
             "name":"unexpectedBetweenItemAndSemicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"semicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenSemicolonAndErrorTokens",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"errorTokens",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterErrorTokens",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":1
    },
    {
       "text":"ImportDecl",
       "id":3,
       "range":{
          "startColumn":1,
          "endRow":1,
          "endColumn":15,
          "startRow":1
       },
       "structure":[
          {
             "name":"unexpectedBeforeAttributes",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"attributes",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenAttributesAndModifiers",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"modifiers",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenModifiersAndImportTok",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"importTok",
             "value":{
                "kind":"importKeyword",
                "text":"import␣"
             }
          },
          {
             "name":"unexpectedBetweenImportTokAndImportKind",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"importKind",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenImportKindAndPath",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"path",
             "value":{
                "text":"AccessPathSyntax"
             },
             "ref":"AccessPathSyntax"
          },
          {
             "name":"unexpectedAfterPath",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"decl",
       "parent":2
    },
    {
       "parent":3,
       "id":4,
       "range":{
          "startColumn":1,
          "endRow":1,
          "endColumn":7,
          "startRow":1
       },
       "text":"import",
       "structure":[
          
       ],
       "token":{
          "kind":"importKeyword",
          "leadingTrivia":"",
          "trailingTrivia":"␣"
       },
       "type":"other"
    },
    {
       "text":"AccessPath",
       "id":5,
       "range":{
          "startColumn":8,
          "endRow":1,
          "endColumn":15,
          "startRow":1
       },
       "structure":[
          {
             "name":"Element",
             "value":{
                "text":"AccessPathComponentSyntax"
             }
          },
          {
             "name":"Count",
             "value":{
                "text":"1"
             }
          }
       ],
       "type":"collection",
       "parent":3
    },
    {
       "text":"AccessPathComponent",
       "id":6,
       "range":{
          "startColumn":8,
          "endRow":1,
          "endColumn":15,
          "startRow":1
       },
       "structure":[
          {
             "name":"unexpectedBeforeName",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"name",
             "value":{
                "kind":"identifier(\"SwiftUI\")",
                "text":"SwiftUI"
             }
          },
          {
             "name":"unexpectedBetweenNameAndTrailingDot",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"trailingDot",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterTrailingDot",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":5
    },
    {
       "parent":6,
       "id":7,
       "range":{
          "startColumn":8,
          "endRow":1,
          "endColumn":15,
          "startRow":1
       },
       "text":"SwiftUI",
       "structure":[
          
       ],
       "token":{
          "kind":"identifier(\"SwiftUI\")",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "text":"CodeBlockItem",
       "id":8,
       "range":{
          "startColumn":1,
          "endRow":13,
          "endColumn":2,
          "startRow":3
       },
       "structure":[
          {
             "name":"unexpectedBeforeItem",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"item",
             "value":{
                "text":"StructDeclSyntax"
             },
             "ref":"StructDeclSyntax"
          },
          {
             "name":"unexpectedBetweenItemAndSemicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"semicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenSemicolonAndErrorTokens",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"errorTokens",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterErrorTokens",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":1
    },
    {
       "text":"StructDecl",
       "id":9,
       "range":{
          "startColumn":1,
          "endRow":13,
          "endColumn":2,
          "startRow":3
       },
       "structure":[
          {
             "name":"unexpectedBeforeAttributes",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"attributes",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenAttributesAndModifiers",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"modifiers",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenModifiersAndStructKeyword",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"structKeyword",
             "value":{
                "kind":"structKeyword",
                "text":"↲↲struct␣"
             }
          },
          {
             "name":"unexpectedBetweenStructKeywordAndIdentifier",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"identifier",
             "value":{
                "kind":"identifier(\"Locked\")",
                "text":"Locked"
             }
          },
          {
             "name":"unexpectedBetweenIdentifierAndGenericParameterClause",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"genericParameterClause",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenGenericParameterClauseAndInheritanceClause",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"inheritanceClause",
             "value":{
                "text":"TypeInheritanceClauseSyntax"
             },
             "ref":"TypeInheritanceClauseSyntax"
          },
          {
             "name":"unexpectedBetweenInheritanceClauseAndGenericWhereClause",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"genericWhereClause",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenGenericWhereClauseAndMembers",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"members",
             "value":{
                "text":"MemberDeclBlockSyntax"
             },
             "ref":"MemberDeclBlockSyntax"
          },
          {
             "name":"unexpectedAfterMembers",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"decl",
       "parent":8
    },
    {
       "parent":9,
       "id":10,
       "range":{
          "startColumn":1,
          "endRow":3,
          "endColumn":7,
          "startRow":3
       },
       "text":"struct",
       "structure":[
          
       ],
       "token":{
          "kind":"structKeyword",
          "leadingTrivia":"↲↲",
          "trailingTrivia":"␣"
       },
       "type":"other"
    },
    {
       "parent":9,
       "id":11,
       "range":{
          "startColumn":8,
          "endRow":3,
          "endColumn":14,
          "startRow":3
       },
       "text":"Locked",
       "structure":[
          
       ],
       "token":{
          "kind":"identifier(\"Locked\")",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "text":"TypeInheritanceClause",
       "id":12,
       "range":{
          "startColumn":14,
          "endRow":3,
          "endColumn":20,
          "startRow":3
       },
       "structure":[
          {
             "name":"unexpectedBeforeColon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"colon",
             "value":{
                "kind":"colon",
                "text":":␣"
             }
          },
          {
             "name":"unexpectedBetweenColonAndInheritedTypeCollection",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"inheritedTypeCollection",
             "value":{
                "text":"InheritedTypeListSyntax"
             },
             "ref":"InheritedTypeListSyntax"
          },
          {
             "name":"unexpectedAfterInheritedTypeCollection",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":9
    },
    {
       "parent":12,
       "id":13,
       "range":{
          "startColumn":14,
          "endRow":3,
          "endColumn":15,
          "startRow":3
       },
       "text":":",
       "structure":[
          
       ],
       "token":{
          "kind":"colon",
          "leadingTrivia":"",
          "trailingTrivia":"␣"
       },
       "type":"other"
    },
    {
       "text":"InheritedTypeList",
       "id":14,
       "range":{
          "startColumn":16,
          "endRow":3,
          "endColumn":20,
          "startRow":3
       },
       "structure":[
          {
             "name":"Element",
             "value":{
                "text":"InheritedTypeSyntax"
             }
          },
          {
             "name":"Count",
             "value":{
                "text":"1"
             }
          }
       ],
       "type":"collection",
       "parent":12
    },
    {
       "text":"InheritedType",
       "id":15,
       "range":{
          "startColumn":16,
          "endRow":3,
          "endColumn":20,
          "startRow":3
       },
       "structure":[
          {
             "name":"unexpectedBeforeTypeName",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"typeName",
             "value":{
                "text":"SimpleTypeIdentifierSyntax"
             },
             "ref":"SimpleTypeIdentifierSyntax"
          },
          {
             "name":"unexpectedBetweenTypeNameAndTrailingComma",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"trailingComma",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterTrailingComma",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":14
    },
    {
       "text":"SimpleTypeIdentifier",
       "id":16,
       "range":{
          "startColumn":16,
          "endRow":3,
          "endColumn":20,
          "startRow":3
       },
       "structure":[
          {
             "name":"unexpectedBeforeName",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"name",
             "value":{
                "kind":"identifier(\"View\")",
                "text":"View␣"
             }
          },
          {
             "name":"unexpectedBetweenNameAndGenericArgumentClause",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"genericArgumentClause",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterGenericArgumentClause",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"type",
       "parent":15
    },
    {
       "parent":16,
       "id":17,
       "range":{
          "startColumn":16,
          "endRow":3,
          "endColumn":20,
          "startRow":3
       },
       "text":"View",
       "structure":[
          
       ],
       "token":{
          "kind":"identifier(\"View\")",
          "leadingTrivia":"",
          "trailingTrivia":"␣"
       },
       "type":"other"
    },
    {
       "text":"MemberDeclBlock",
       "id":18,
       "range":{
          "startColumn":21,
          "endRow":13,
          "endColumn":2,
          "startRow":3
       },
       "structure":[
          {
             "name":"unexpectedBeforeLeftBrace",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"leftBrace",
             "value":{
                "kind":"leftBrace",
                "text":"{"
             }
          },
          {
             "name":"unexpectedBetweenLeftBraceAndMembers",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"members",
             "value":{
                "text":"MemberDeclListSyntax"
             },
             "ref":"MemberDeclListSyntax"
          },
          {
             "name":"unexpectedBetweenMembersAndRightBrace",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"rightBrace",
             "value":{
                "kind":"rightBrace",
                "text":"↲}"
             }
          },
          {
             "name":"unexpectedAfterRightBrace",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":9
    },
    {
       "parent":18,
       "id":19,
       "range":{
          "startColumn":21,
          "endRow":3,
          "endColumn":22,
          "startRow":3
       },
       "text":"{",
       "structure":[
          
       ],
       "token":{
          "kind":"leftBrace",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "text":"MemberDeclList",
       "id":20,
       "range":{
          "startColumn":5,
          "endRow":12,
          "endColumn":6,
          "startRow":4
       },
       "structure":[
          {
             "name":"Element",
             "value":{
                "text":"MemberDeclListItemSyntax"
             }
          },
          {
             "name":"Count",
             "value":{
                "text":"1"
             }
          }
       ],
       "type":"collection",
       "parent":18
    },
    {
       "text":"MemberDeclListItem",
       "id":21,
       "range":{
          "startColumn":5,
          "endRow":12,
          "endColumn":6,
          "startRow":4
       },
       "structure":[
          {
             "name":"unexpectedBeforeDecl",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"decl",
             "value":{
                "text":"VariableDeclSyntax"
             },
             "ref":"VariableDeclSyntax"
          },
          {
             "name":"unexpectedBetweenDeclAndSemicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"semicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterSemicolon",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":20
    },
    {
       "text":"VariableDecl",
       "id":22,
       "range":{
          "startColumn":5,
          "endRow":12,
          "endColumn":6,
          "startRow":4
       },
       "structure":[
          {
             "name":"unexpectedBeforeAttributes",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"attributes",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenAttributesAndModifiers",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"modifiers",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenModifiersAndLetOrVarKeyword",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"letOrVarKeyword",
             "value":{
                "kind":"varKeyword",
                "text":"↲␣␣␣␣var␣"
             }
          },
          {
             "name":"unexpectedBetweenLetOrVarKeywordAndBindings",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"bindings",
             "value":{
                "text":"PatternBindingListSyntax"
             },
             "ref":"PatternBindingListSyntax"
          },
          {
             "name":"unexpectedAfterBindings",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"decl",
       "parent":21
    },
    {
       "parent":22,
       "id":23,
       "range":{
          "startColumn":5,
          "endRow":4,
          "endColumn":8,
          "startRow":4
       },
       "text":"var",
       "structure":[
          
       ],
       "token":{
          "kind":"varKeyword",
          "leadingTrivia":"↲␣␣␣␣",
          "trailingTrivia":"␣"
       },
       "type":"other"
    },
    {
       "text":"PatternBindingList",
       "id":24,
       "range":{
          "startColumn":9,
          "endRow":12,
          "endColumn":6,
          "startRow":4
       },
       "structure":[
          {
             "name":"Element",
             "value":{
                "text":"PatternBindingSyntax"
             }
          },
          {
             "name":"Count",
             "value":{
                "text":"1"
             }
          }
       ],
       "type":"collection",
       "parent":22
    },
    {
       "text":"PatternBinding",
       "id":25,
       "range":{
          "startColumn":9,
          "endRow":12,
          "endColumn":6,
          "startRow":4
       },
       "structure":[
          {
             "name":"unexpectedBeforePattern",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"pattern",
             "value":{
                "text":"IdentifierPatternSyntax"
             },
             "ref":"IdentifierPatternSyntax"
          },
          {
             "name":"unexpectedBetweenPatternAndTypeAnnotation",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"typeAnnotation",
             "value":{
                "text":"TypeAnnotationSyntax"
             },
             "ref":"TypeAnnotationSyntax"
          },
          {
             "name":"unexpectedBetweenTypeAnnotationAndInitializer",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"initializer",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenInitializerAndAccessor",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"accessor",
             "value":{
                "text":"CodeBlockSyntax"
             },
             "ref":"CodeBlockSyntax"
          },
          {
             "name":"unexpectedBetweenAccessorAndTrailingComma",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"trailingComma",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterTrailingComma",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":24
    },
    {
       "text":"IdentifierPattern",
       "id":26,
       "range":{
          "startColumn":9,
          "endRow":4,
          "endColumn":13,
          "startRow":4
       },
       "structure":[
          {
             "name":"unexpectedBeforeIdentifier",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"identifier",
             "value":{
                "kind":"identifier(\"body\")",
                "text":"body"
             }
          },
          {
             "name":"unexpectedAfterIdentifier",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"pattern",
       "parent":25
    },
    {
       "parent":26,
       "id":27,
       "range":{
          "startColumn":9,
          "endRow":4,
          "endColumn":13,
          "startRow":4
       },
       "text":"body",
       "structure":[
          
       ],
       "token":{
          "kind":"identifier(\"body\")",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "text":"TypeAnnotation",
       "id":28,
       "range":{
          "startColumn":13,
          "endRow":4,
          "endColumn":24,
          "startRow":4
       },
       "structure":[
          {
             "name":"unexpectedBeforeColon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"colon",
             "value":{
                "kind":"colon",
                "text":":␣"
             }
          },
          {
             "name":"unexpectedBetweenColonAndType",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"type",
             "value":{
                "text":"ConstrainedSugarTypeSyntax"
             },
             "ref":"ConstrainedSugarTypeSyntax"
          },
          {
             "name":"unexpectedAfterType",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":25
    },
    {
       "parent":28,
       "id":29,
       "range":{
          "startColumn":13,
          "endRow":4,
          "endColumn":14,
          "startRow":4
       },
       "text":":",
       "structure":[
          
       ],
       "token":{
          "kind":"colon",
          "leadingTrivia":"",
          "trailingTrivia":"␣"
       },
       "type":"other"
    },
    {
       "text":"ConstrainedSugarType",
       "id":30,
       "range":{
          "startColumn":15,
          "endRow":4,
          "endColumn":24,
          "startRow":4
       },
       "structure":[
          {
             "name":"unexpectedBeforeSomeOrAnySpecifier",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"someOrAnySpecifier",
             "value":{
                "kind":"identifier(\"some\")",
                "text":"some␣"
             }
          },
          {
             "name":"unexpectedBetweenSomeOrAnySpecifierAndBaseType",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"baseType",
             "value":{
                "text":"SimpleTypeIdentifierSyntax"
             },
             "ref":"SimpleTypeIdentifierSyntax"
          },
          {
             "name":"unexpectedAfterBaseType",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"type",
       "parent":28
    },
    {
       "parent":30,
       "id":31,
       "range":{
          "startColumn":15,
          "endRow":4,
          "endColumn":19,
          "startRow":4
       },
       "text":"some",
       "structure":[
          
       ],
       "token":{
          "kind":"identifier(\"some\")",
          "leadingTrivia":"",
          "trailingTrivia":"␣"
       },
       "type":"other"
    },
    {
       "text":"SimpleTypeIdentifier",
       "id":32,
       "range":{
          "startColumn":20,
          "endRow":4,
          "endColumn":24,
          "startRow":4
       },
       "structure":[
          {
             "name":"unexpectedBeforeName",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"name",
             "value":{
                "kind":"identifier(\"View\")",
                "text":"View␣"
             }
          },
          {
             "name":"unexpectedBetweenNameAndGenericArgumentClause",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"genericArgumentClause",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterGenericArgumentClause",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"type",
       "parent":30
    },
    {
       "parent":32,
       "id":33,
       "range":{
          "startColumn":20,
          "endRow":4,
          "endColumn":24,
          "startRow":4
       },
       "text":"View",
       "structure":[
          
       ],
       "token":{
          "kind":"identifier(\"View\")",
          "leadingTrivia":"",
          "trailingTrivia":"␣"
       },
       "type":"other"
    },
    {
       "text":"CodeBlock",
       "id":34,
       "range":{
          "startColumn":25,
          "endRow":12,
          "endColumn":6,
          "startRow":4
       },
       "structure":[
          {
             "name":"unexpectedBeforeLeftBrace",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"leftBrace",
             "value":{
                "kind":"leftBrace",
                "text":"{"
             }
          },
          {
             "name":"unexpectedBetweenLeftBraceAndStatements",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"statements",
             "value":{
                "text":"CodeBlockItemListSyntax"
             },
             "ref":"CodeBlockItemListSyntax"
          },
          {
             "name":"unexpectedBetweenStatementsAndRightBrace",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"rightBrace",
             "value":{
                "kind":"rightBrace",
                "text":"↲␣␣␣␣}"
             }
          },
          {
             "name":"unexpectedAfterRightBrace",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":25
    },
    {
       "parent":34,
       "id":35,
       "range":{
          "startColumn":25,
          "endRow":4,
          "endColumn":26,
          "startRow":4
       },
       "text":"{",
       "structure":[
          
       ],
       "token":{
          "kind":"leftBrace",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "text":"CodeBlockItemList",
       "id":36,
       "range":{
          "startColumn":9,
          "endRow":11,
          "endColumn":10,
          "startRow":5
       },
       "structure":[
          {
             "name":"Element",
             "value":{
                "text":"CodeBlockItemSyntax"
             }
          },
          {
             "name":"Count",
             "value":{
                "text":"1"
             }
          }
       ],
       "type":"collection",
       "parent":34
    },
    {
       "text":"CodeBlockItem",
       "id":37,
       "range":{
          "startColumn":9,
          "endRow":11,
          "endColumn":10,
          "startRow":5
       },
       "structure":[
          {
             "name":"unexpectedBeforeItem",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"item",
             "value":{
                "text":"FunctionCallExprSyntax"
             },
             "ref":"FunctionCallExprSyntax"
          },
          {
             "name":"unexpectedBetweenItemAndSemicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"semicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenSemicolonAndErrorTokens",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"errorTokens",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterErrorTokens",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":36
    },
    {
       "text":"FunctionCallExpr",
       "id":38,
       "range":{
          "startColumn":9,
          "endRow":11,
          "endColumn":10,
          "startRow":5
       },
       "structure":[
          {
             "name":"unexpectedBeforeCalledExpression",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"calledExpression",
             "value":{
                "text":"IdentifierExprSyntax"
             },
             "ref":"IdentifierExprSyntax"
          },
          {
             "name":"unexpectedBetweenCalledExpressionAndLeftParen",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"leftParen",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenLeftParenAndArgumentList",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"argumentList",
             "value":{
                "text":"TupleExprElementListSyntax"
             },
             "ref":"TupleExprElementListSyntax"
          },
          {
             "name":"unexpectedBetweenArgumentListAndRightParen",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"rightParen",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenRightParenAndTrailingClosure",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"trailingClosure",
             "value":{
                "text":"ClosureExprSyntax"
             },
             "ref":"ClosureExprSyntax"
          },
          {
             "name":"unexpectedBetweenTrailingClosureAndAdditionalTrailingClosures",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"additionalTrailingClosures",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterAdditionalTrailingClosures",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"expr",
       "parent":37
    },
    {
       "text":"IdentifierExpr",
       "id":39,
       "range":{
          "startColumn":9,
          "endRow":5,
          "endColumn":15,
          "startRow":5
       },
       "structure":[
          {
             "name":"unexpectedBeforeIdentifier",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"identifier",
             "value":{
                "kind":"identifier(\"HStack\")",
                "text":"↲␣␣␣␣␣␣␣␣HStack␣"
             }
          },
          {
             "name":"unexpectedBetweenIdentifierAndDeclNameArguments",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"declNameArguments",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterDeclNameArguments",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"expr",
       "parent":38
    },
    {
       "parent":39,
       "id":40,
       "range":{
          "startColumn":9,
          "endRow":5,
          "endColumn":15,
          "startRow":5
       },
       "text":"HStack",
       "structure":[
          
       ],
       "token":{
          "kind":"identifier(\"HStack\")",
          "leadingTrivia":"↲␣␣␣␣␣␣␣␣",
          "trailingTrivia":"␣"
       },
       "type":"other"
    },
    {
       "text":"TupleExprElementList",
       "id":41,
       "range":{
          "startColumn":16,
          "endRow":5,
          "endColumn":16,
          "startRow":5
       },
       "structure":[
          {
             "name":"Element",
             "value":{
                "text":"TupleExprElementSyntax"
             }
          },
          {
             "name":"Count",
             "value":{
                "text":"0"
             }
          }
       ],
       "type":"collection",
       "parent":38
    },
    {
       "text":"ClosureExpr",
       "id":42,
       "range":{
          "startColumn":16,
          "endRow":11,
          "endColumn":10,
          "startRow":5
       },
       "structure":[
          {
             "name":"unexpectedBeforeLeftBrace",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"leftBrace",
             "value":{
                "kind":"leftBrace",
                "text":"{"
             }
          },
          {
             "name":"unexpectedBetweenLeftBraceAndSignature",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"signature",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenSignatureAndStatements",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"statements",
             "value":{
                "text":"CodeBlockItemListSyntax"
             },
             "ref":"CodeBlockItemListSyntax"
          },
          {
             "name":"unexpectedBetweenStatementsAndRightBrace",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"rightBrace",
             "value":{
                "kind":"rightBrace",
                "text":"↲␣␣␣␣␣␣␣␣}"
             }
          },
          {
             "name":"unexpectedAfterRightBrace",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"expr",
       "parent":38
    },
    {
       "parent":42,
       "id":43,
       "range":{
          "startColumn":16,
          "endRow":5,
          "endColumn":17,
          "startRow":5
       },
       "text":"{",
       "structure":[
          
       ],
       "token":{
          "kind":"leftBrace",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "text":"CodeBlockItemList",
       "id":44,
       "range":{
          "startColumn":13,
          "endRow":10,
          "endColumn":21,
          "startRow":6
       },
       "structure":[
          {
             "name":"Element",
             "value":{
                "text":"CodeBlockItemSyntax"
             }
          },
          {
             "name":"Count",
             "value":{
                "text":"3"
             }
          }
       ],
       "type":"collection",
       "parent":42
    },
    {
       "text":"CodeBlockItem",
       "id":45,
       "range":{
          "startColumn":13,
          "endRow":6,
          "endColumn":21,
          "startRow":6
       },
       "structure":[
          {
             "name":"unexpectedBeforeItem",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"item",
             "value":{
                "text":"FunctionCallExprSyntax"
             },
             "ref":"FunctionCallExprSyntax"
          },
          {
             "name":"unexpectedBetweenItemAndSemicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"semicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenSemicolonAndErrorTokens",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"errorTokens",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterErrorTokens",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":44
    },
    {
       "text":"FunctionCallExpr",
       "id":46,
       "range":{
          "startColumn":13,
          "endRow":6,
          "endColumn":21,
          "startRow":6
       },
       "structure":[
          {
             "name":"unexpectedBeforeCalledExpression",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"calledExpression",
             "value":{
                "text":"IdentifierExprSyntax"
             },
             "ref":"IdentifierExprSyntax"
          },
          {
             "name":"unexpectedBetweenCalledExpressionAndLeftParen",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"leftParen",
             "value":{
                "kind":"leftParen",
                "text":"("
             }
          },
          {
             "name":"unexpectedBetweenLeftParenAndArgumentList",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"argumentList",
             "value":{
                "text":"TupleExprElementListSyntax"
             },
             "ref":"TupleExprElementListSyntax"
          },
          {
             "name":"unexpectedBetweenArgumentListAndRightParen",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"rightParen",
             "value":{
                "kind":"rightParen",
                "text":")"
             }
          },
          {
             "name":"unexpectedBetweenRightParenAndTrailingClosure",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"trailingClosure",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenTrailingClosureAndAdditionalTrailingClosures",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"additionalTrailingClosures",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterAdditionalTrailingClosures",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"expr",
       "parent":45
    },
    {
       "text":"IdentifierExpr",
       "id":47,
       "range":{
          "startColumn":13,
          "endRow":6,
          "endColumn":19,
          "startRow":6
       },
       "structure":[
          {
             "name":"unexpectedBeforeIdentifier",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"identifier",
             "value":{
                "kind":"identifier(\"Spacer\")",
                "text":"↲␣␣␣␣␣␣␣␣␣␣␣␣Spacer"
             }
          },
          {
             "name":"unexpectedBetweenIdentifierAndDeclNameArguments",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"declNameArguments",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterDeclNameArguments",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"expr",
       "parent":46
    },
    {
       "parent":47,
       "id":48,
       "range":{
          "startColumn":13,
          "endRow":6,
          "endColumn":19,
          "startRow":6
       },
       "text":"Spacer",
       "structure":[
          
       ],
       "token":{
          "kind":"identifier(\"Spacer\")",
          "leadingTrivia":"↲␣␣␣␣␣␣␣␣␣␣␣␣",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "parent":46,
       "id":49,
       "range":{
          "startColumn":19,
          "endRow":6,
          "endColumn":20,
          "startRow":6
       },
       "text":"(",
       "structure":[
          
       ],
       "token":{
          "kind":"leftParen",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "text":"TupleExprElementList",
       "id":50,
       "range":{
          "startColumn":20,
          "endRow":6,
          "endColumn":20,
          "startRow":6
       },
       "structure":[
          {
             "name":"Element",
             "value":{
                "text":"TupleExprElementSyntax"
             }
          },
          {
             "name":"Count",
             "value":{
                "text":"0"
             }
          }
       ],
       "type":"collection",
       "parent":46
    },
    {
       "parent":46,
       "id":51,
       "range":{
          "startColumn":20,
          "endRow":6,
          "endColumn":21,
          "startRow":6
       },
       "text":")",
       "structure":[
          
       ],
       "token":{
          "kind":"rightParen",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "text":"CodeBlockItem",
       "id":52,
       "range":{
          "startColumn":13,
          "endRow":8,
          "endColumn":29,
          "startRow":8
       },
       "structure":[
          {
             "name":"unexpectedBeforeItem",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"item",
             "value":{
                "text":"FunctionCallExprSyntax"
             },
             "ref":"FunctionCallExprSyntax"
          },
          {
             "name":"unexpectedBetweenItemAndSemicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"semicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenSemicolonAndErrorTokens",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"errorTokens",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterErrorTokens",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":44
    },
    {
       "text":"FunctionCallExpr",
       "id":53,
       "range":{
          "startColumn":13,
          "endRow":8,
          "endColumn":29,
          "startRow":8
       },
       "structure":[
          {
             "name":"unexpectedBeforeCalledExpression",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"calledExpression",
             "value":{
                "text":"IdentifierExprSyntax"
             },
             "ref":"IdentifierExprSyntax"
          },
          {
             "name":"unexpectedBetweenCalledExpressionAndLeftParen",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"leftParen",
             "value":{
                "kind":"leftParen",
                "text":"("
             }
          },
          {
             "name":"unexpectedBetweenLeftParenAndArgumentList",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"argumentList",
             "value":{
                "text":"TupleExprElementListSyntax"
             },
             "ref":"TupleExprElementListSyntax"
          },
          {
             "name":"unexpectedBetweenArgumentListAndRightParen",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"rightParen",
             "value":{
                "kind":"rightParen",
                "text":")"
             }
          },
          {
             "name":"unexpectedBetweenRightParenAndTrailingClosure",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"trailingClosure",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenTrailingClosureAndAdditionalTrailingClosures",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"additionalTrailingClosures",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterAdditionalTrailingClosures",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"expr",
       "parent":52
    },
    {
       "text":"IdentifierExpr",
       "id":54,
       "range":{
          "startColumn":13,
          "endRow":8,
          "endColumn":17,
          "startRow":8
       },
       "structure":[
          {
             "name":"unexpectedBeforeIdentifier",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"identifier",
             "value":{
                "kind":"identifier(\"Text\")",
                "text":"↲␣␣␣␣␣␣␣␣␣␣␣␣↲␣␣␣␣␣␣␣␣␣␣␣␣Text"
             }
          },
          {
             "name":"unexpectedBetweenIdentifierAndDeclNameArguments",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"declNameArguments",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterDeclNameArguments",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"expr",
       "parent":53
    },
    {
       "parent":54,
       "id":55,
       "range":{
          "startColumn":13,
          "endRow":8,
          "endColumn":17,
          "startRow":8
       },
       "text":"Text",
       "structure":[
          
       ],
       "token":{
          "kind":"identifier(\"Text\")",
          "leadingTrivia":"↲␣␣␣␣␣␣␣␣␣␣␣␣↲␣␣␣␣␣␣␣␣␣␣␣␣",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "parent":53,
       "id":56,
       "range":{
          "startColumn":17,
          "endRow":8,
          "endColumn":18,
          "startRow":8
       },
       "text":"(",
       "structure":[
          
       ],
       "token":{
          "kind":"leftParen",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "text":"TupleExprElementList",
       "id":57,
       "range":{
          "startColumn":18,
          "endRow":8,
          "endColumn":28,
          "startRow":8
       },
       "structure":[
          {
             "name":"Element",
             "value":{
                "text":"TupleExprElementSyntax"
             }
          },
          {
             "name":"Count",
             "value":{
                "text":"1"
             }
          }
       ],
       "type":"collection",
       "parent":53
    },
    {
       "text":"TupleExprElement",
       "id":58,
       "range":{
          "startColumn":18,
          "endRow":8,
          "endColumn":28,
          "startRow":8
       },
       "structure":[
          {
             "name":"unexpectedBeforeLabel",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"label",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenLabelAndColon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"colon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenColonAndExpression",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"expression",
             "value":{
                "text":"StringLiteralExprSyntax"
             },
             "ref":"StringLiteralExprSyntax"
          },
          {
             "name":"unexpectedBetweenExpressionAndTrailingComma",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"trailingComma",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterTrailingComma",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":57
    },
    {
       "text":"StringLiteralExpr",
       "id":59,
       "range":{
          "startColumn":18,
          "endRow":8,
          "endColumn":28,
          "startRow":8
       },
       "structure":[
          {
             "name":"unexpectedBeforeOpenDelimiter",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"openDelimiter",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenOpenDelimiterAndOpenQuote",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"openQuote",
             "value":{
                "kind":"stringQuote",
                "text":"\""
             }
          },
          {
             "name":"unexpectedBetweenOpenQuoteAndSegments",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"segments",
             "value":{
                "text":"StringLiteralSegmentsSyntax"
             },
             "ref":"StringLiteralSegmentsSyntax"
          },
          {
             "name":"unexpectedBetweenSegmentsAndCloseQuote",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"closeQuote",
             "value":{
                "kind":"stringQuote",
                "text":"\""
             }
          },
          {
             "name":"unexpectedBetweenCloseQuoteAndCloseDelimiter",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"closeDelimiter",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterCloseDelimiter",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"expr",
       "parent":58
    },
    {
       "parent":59,
       "id":60,
       "range":{
          "startColumn":18,
          "endRow":8,
          "endColumn":19,
          "startRow":8
       },
       "text":"\"",
       "structure":[
          
       ],
       "token":{
          "kind":"stringQuote",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "text":"StringLiteralSegments",
       "id":61,
       "range":{
          "startColumn":19,
          "endRow":8,
          "endColumn":27,
          "startRow":8
       },
       "structure":[
          {
             "name":"Element",
             "value":{
                "text":"Element"
             }
          },
          {
             "name":"Count",
             "value":{
                "text":"1"
             }
          }
       ],
       "type":"collection",
       "parent":59
    },
    {
       "text":"StringSegment",
       "id":62,
       "range":{
          "startColumn":19,
          "endRow":8,
          "endColumn":27,
          "startRow":8
       },
       "structure":[
          {
             "name":"unexpectedBeforeContent",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"content",
             "value":{
                "kind":"stringSegment(\"Hello...\")",
                "text":"Hello..."
             }
          },
          {
             "name":"unexpectedAfterContent",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":61
    },
    {
       "parent":62,
       "id":63,
       "range":{
          "startColumn":19,
          "endRow":8,
          "endColumn":27,
          "startRow":8
       },
       "text":"Hello...",
       "structure":[
          
       ],
       "token":{
          "kind":"stringSegment(\"Hello...\")",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "parent":59,
       "id":64,
       "range":{
          "startColumn":27,
          "endRow":8,
          "endColumn":28,
          "startRow":8
       },
       "text":"\"",
       "structure":[
          
       ],
       "token":{
          "kind":"stringQuote",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "parent":53,
       "id":65,
       "range":{
          "startColumn":28,
          "endRow":8,
          "endColumn":29,
          "startRow":8
       },
       "text":")",
       "structure":[
          
       ],
       "token":{
          "kind":"rightParen",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "text":"CodeBlockItem",
       "id":66,
       "range":{
          "startColumn":13,
          "endRow":10,
          "endColumn":21,
          "startRow":10
       },
       "structure":[
          {
             "name":"unexpectedBeforeItem",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"item",
             "value":{
                "text":"FunctionCallExprSyntax"
             },
             "ref":"FunctionCallExprSyntax"
          },
          {
             "name":"unexpectedBetweenItemAndSemicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"semicolon",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenSemicolonAndErrorTokens",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"errorTokens",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterErrorTokens",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"other",
       "parent":44
    },
    {
       "text":"FunctionCallExpr",
       "id":67,
       "range":{
          "startColumn":13,
          "endRow":10,
          "endColumn":21,
          "startRow":10
       },
       "structure":[
          {
             "name":"unexpectedBeforeCalledExpression",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"calledExpression",
             "value":{
                "text":"IdentifierExprSyntax"
             },
             "ref":"IdentifierExprSyntax"
          },
          {
             "name":"unexpectedBetweenCalledExpressionAndLeftParen",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"leftParen",
             "value":{
                "kind":"leftParen",
                "text":"("
             }
          },
          {
             "name":"unexpectedBetweenLeftParenAndArgumentList",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"argumentList",
             "value":{
                "text":"TupleExprElementListSyntax"
             },
             "ref":"TupleExprElementListSyntax"
          },
          {
             "name":"unexpectedBetweenArgumentListAndRightParen",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"rightParen",
             "value":{
                "kind":"rightParen",
                "text":")"
             }
          },
          {
             "name":"unexpectedBetweenRightParenAndTrailingClosure",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"trailingClosure",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedBetweenTrailingClosureAndAdditionalTrailingClosures",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"additionalTrailingClosures",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterAdditionalTrailingClosures",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"expr",
       "parent":66
    },
    {
       "text":"IdentifierExpr",
       "id":68,
       "range":{
          "startColumn":13,
          "endRow":10,
          "endColumn":19,
          "startRow":10
       },
       "structure":[
          {
             "name":"unexpectedBeforeIdentifier",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"identifier",
             "value":{
                "kind":"identifier(\"Spacer\")",
                "text":"↲␣␣␣␣␣␣␣␣␣␣␣␣↲␣␣␣␣␣␣␣␣␣␣␣␣Spacer"
             }
          },
          {
             "name":"unexpectedBetweenIdentifierAndDeclNameArguments",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"declNameArguments",
             "value":{
                "text":"nil"
             }
          },
          {
             "name":"unexpectedAfterDeclNameArguments",
             "value":{
                "text":"nil"
             }
          }
       ],
       "type":"expr",
       "parent":67
    },
    {
       "parent":68,
       "id":69,
       "range":{
          "startColumn":13,
          "endRow":10,
          "endColumn":19,
          "startRow":10
       },
       "text":"Spacer",
       "structure":[
          
       ],
       "token":{
          "kind":"identifier(\"Spacer\")",
          "leadingTrivia":"↲␣␣␣␣␣␣␣␣␣␣␣␣↲␣␣␣␣␣␣␣␣␣␣␣␣",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "parent":67,
       "id":70,
       "range":{
          "startColumn":19,
          "endRow":10,
          "endColumn":20,
          "startRow":10
       },
       "text":"(",
       "structure":[
          
       ],
       "token":{
          "kind":"leftParen",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "text":"TupleExprElementList",
       "id":71,
       "range":{
          "startColumn":20,
          "endRow":10,
          "endColumn":20,
          "startRow":10
       },
       "structure":[
          {
             "name":"Element",
             "value":{
                "text":"TupleExprElementSyntax"
             }
          },
          {
             "name":"Count",
             "value":{
                "text":"0"
             }
          }
       ],
       "type":"collection",
       "parent":67
    },
    {
       "parent":67,
       "id":72,
       "range":{
          "startColumn":20,
          "endRow":10,
          "endColumn":21,
          "startRow":10
       },
       "text":")",
       "structure":[
          
       ],
       "token":{
          "kind":"rightParen",
          "leadingTrivia":"",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "parent":42,
       "id":73,
       "range":{
          "startColumn":9,
          "endRow":11,
          "endColumn":10,
          "startRow":11
       },
       "text":"}",
       "structure":[
          
       ],
       "token":{
          "kind":"rightBrace",
          "leadingTrivia":"↲␣␣␣␣␣␣␣␣",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "parent":34,
       "id":74,
       "range":{
          "startColumn":5,
          "endRow":12,
          "endColumn":6,
          "startRow":12
       },
       "text":"}",
       "structure":[
          
       ],
       "token":{
          "kind":"rightBrace",
          "leadingTrivia":"↲␣␣␣␣",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "parent":18,
       "id":75,
       "range":{
          "startColumn":1,
          "endRow":13,
          "endColumn":2,
          "startRow":13
       },
       "text":"}",
       "structure":[
          
       ],
       "token":{
          "kind":"rightBrace",
          "leadingTrivia":"↲",
          "trailingTrivia":""
       },
       "type":"other"
    },
    {
       "parent":0,
       "id":76,
       "range":{
          "startColumn":1,
          "endRow":14,
          "endColumn":1,
          "startRow":14
       },
       "text":"",
       "structure":[
          
       ],
       "token":{
          "kind":"eof",
          "leadingTrivia":"↲",
          "trailingTrivia":""
       },
       "type":"other"
    }
]

export { textBetweenSpacersHstack }